FORMAT: 1A
HOST: http://hostname:3000

# Gitty API

The github event browser.

# Group Events

## Events [/api/events/{?repoId,type,limit,skip}]

### Get Events [GET]

Browse for events.

+ Parameters
    + repoId (number, optional) - Filter by a repository id.
    + type (optional) - Filter by an event type.
    + limit (number, optional) - Limit by number of documents to be fetched. Max limit allowed is 50.
        + Default: 10
    + skip (optional) - Skip number of documents before applying the limit.
        + Default: 0


+ Response 200 (application/json)

    + Body

            {
                "count": 230,
                "data": [{
                    "_id":"57eb5235e9f1ce82d1988f39",
                    "id":"2489651045",
                    "type":"CreateEvent",
                    "actor":{
                        "id":665991,
                        "login":"petroav",
                        "gravatar_id":"",
                        "url":"https://api.github.com/users/petroav",
                        "avatar_url":"https://avatars.githubusercontent.com/u/665991?"
                    },
                    "repo":{
                        "id":28688495,
                        "name":"petroav/6.828",
                        "url":"https://api.github.com/repos/petroav/6.828"
                    },
                    "payload":{
                        "ref":"master",
                        "ref_type":"branch",
                        "master_branch":"master",
                        "description":"Solution to homework and assignments from MIT's 6.828 (Operating Systems Engineering). Done in my spare time.",
                        "pusher_type":"user"
                    },
                    "public":true,
                    "created_at":"2015-01-01T15:00:00Z"
                }
                .
                .
                .
                ]
            }
